max_epochs: 3
batch_size: 16
max_length: 128
accelerator: "auto"
devices: 1
log_every_n_steps: 10
precision: "16-mixed"
limit_train_batches: 1.0
limit_val_batches: 1.0

logger:
  project: "lucky-ai"
  enabled: True
  log_model: False
